# Based on https://github.com/OwlPlug/owlplug-scanner/blob/master/.github/workflows/main.yml
name: RdPiano

on: 
  push:
    branches: 
      - '**'

jobs:
  build-win:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        fetch-depth: 0
        submodules: recursive
    - name: "Download Projucer"
      run: |
           cd rdpiano_juce
           git clone -b 8.0.1 --depth 1 https://github.com/juce-framework/JUCE JUCE
           bash -ex ./build/download-projucer.sh
      shell: bash
      env:
        OS: windows
    - name: "Build RdPiano"
      run: sh -ex ./rdpiano_juce/build/build-win.sh
      shell: bash
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: RdPiano-win
        path: |
              ./rdpiano_juce/Builds/VisualStudio2022/x64/Release/VST3/rdpiano_juce.vst3
              ./rdpiano_juce/Builds/VisualStudio2022/x64/Release/Standalone Plugin/rdpiano_juce.exe
  build-osx:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        fetch-depth: 0
        submodules: recursive
    - name: "Download Projucer"
      run: |
           cd rdpiano_juce
           git clone -b 8.0.1 --depth 1 https://github.com/juce-framework/JUCE JUCE
           bash -ex ./build/download-projucer.sh
      shell: bash
      env:
        OS: osx
    - name: "Build macOS"
      run: sh -ex ./rdpiano_juce/build/build-osx.sh
      shell: bash
    - name: "zip macOS"
      run: |
           cd ./rdpiano_juce/Builds/MacOSX/build/Release/
           zip -r rdpiano_juce.vst3.macOS.zip rdpiano_juce.vst3
           zip -r rdpiano_juce.component.macOS.zip rdpiano_juce.component
           zip -r rdpiano_juce.app.macOS.zip rdpiano_juce.app
           cd -
      shell: bash
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: RdPiano-osx
        path: |
              ./rdpiano_juce/Builds/MacOSX/build/Release/rdpiano_juce.vst3.macOS.zip
              ./rdpiano_juce/Builds/MacOSX/build/Release/rdpiano_juce.component.macOS.zip
              ./rdpiano_juce/Builds/MacOSX/build/Release/rdpiano_juce.app.macOS.zip
  release:
    name: "Release"
    needs: [build-win, build-osx]
    if: github.ref == 'refs/heads/main'
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Retrieve artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./rdpiano_juce/build
          pattern: "*"
          merge-multiple: true
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: latest
          title: RdPiano Latest
          files: |
                 RdPiano-osx
                 RdPiano-win
